return {}
-- return {
--   "olimorris/codecompanion.nvim",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "nvim-treesitter/nvim-treesitter",
--   },
--   config = function()
--     require("codecompanion").setup({
--     strategies = {
--       chat = {
--         adapter = "deepseek",
--       },
--       inline = {
--         adapter = "copilot",
--       },
--     },
--   })
--   end,
-- }
